library(tidyverse)
data <- read_csv("~/GitHub/ag-problems-semester/PilotPlot1_summer_2019_PlantHeight-SexRatio.csv")
rm(VarietyTrial1_summer_2019_Flowering)
PP1_H <- select(data, Year, Month, Day, Block, Row, Column, Rep, Height_cm)
mutate(PP1_H, Avg_Heights = Height_cm /10)
Puma3_PP1_H <- filter (PP1_H, Block %in% c(1, 2, 3, 4), Row %in% c(1, 4, 4, 4))
Puma3_PP1_H <- filter (Puma3_PP1_H, Column %in% c("B", "c", "B", "D"))
Puma3_PP1_H <- filter (PP1_H, Block %in% c(1, 2, 3, 4), Row %in% c(1, 4, 4, 4), Column %in% c("B", "c", "B", "D"))
Puma3_PP1_H <- filter (Puma3_PP1_H, Row == 1, Column == "B")
Puma3_PP1_H <- filter (PP1_H, Block %in% c(1, 2, 3, 4), Row %in% c(1, 4, 1, 4), Column %in% c("B", "c", "B", "D"))
Puma3_PP1_H <- filter (PP1_H, Block %in% c(1, 2, 3, 4), Row %in% c(1, 4, 1, 4) & Column %in% c("B", "C", "B", "D"))
Puma3_PP1_HO <- filter (Puma3_PP1_H, Row %in% c(1, 4, 1, 4), Column %in% c("B", "C", "B", "D")) 
view(Puma3_PP1_H)
Puma3_PP1_HO <- filter (Puma3_PP1_H, Block %in% c(1, 2, 3, 4) & Row %in% c(1, 4, 1, 4) & Column %in% c('B', 'C', 'B', 'D'))
by_day <- group_by(PP1_H, Year, Month, Day)
Height_Over_Time <- summarize(by_day, Average = mean(Height_cm, na.rm = TRUE), SD = sd(Height_cm, na.rm = TRUE))
